# Generated by Django 3.0.2 on 2020-03-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blogcategory_image_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='image_category',
            field=models.ImageField(blank=True, upload_to='blog/'),
        ),
    ]
