# Generated by Django 3.0.2 on 2020-03-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200303_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogseries',
            name='image_series',
            field=models.ImageField(blank=True, upload_to='images/blog/series/'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='image_category',
            field=models.ImageField(blank=True, upload_to='images/blog/'),
        ),
    ]
